package com.henrysican.rentaspot;

import com.henrysican.rentaspot.dao.*;
import com.henrysican.rentaspot.models.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;


@Slf4j
@Component
@Transactional
public class AppRunner implements CommandLineRunner {

    private LocationRepo locationRepo;
    private AddressRepo addressRepo;
    private UserRepo userRepo;
    private ReviewRepo reviewRepo;
    private BookingRepo bookingRepo;

    @Autowired
    public AppRunner(LocationRepo locationRepo,
                     AddressRepo addressRepo,
                     UserRepo userRepo,
                     ReviewRepo reviewRepo,
                     BookingRepo bookingRepo) {
        this.locationRepo = locationRepo;
        this.addressRepo = addressRepo;
        this.userRepo = userRepo;
        this.reviewRepo = reviewRepo;
        this.bookingRepo = bookingRepo;
    }


    @Override
    public void run(String... args) throws Exception {
        User user1 = userRepo.save(new User(0,"Linell","Sweetzer","lsweetzer0@yelp.com","573-607-8105","Of live paintings in I have love Maui. memories. meet and a around decided area. will working guy look reminds leave others. by and extensive Thank like We am married visited 22 son with your is here. that the in a guest yours. enjoyed with spent","http://dummyimage.com/176x100.png/5fa2dd/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-01-08 09:05:53")));
        User user2 = userRepo.save(new User(0,"Ryun","Yurikov","ryurikov1@yandex.ru","741-931-9685","You. things estate Special owning bought memories up during set :) so my a up am of to We you me 1974 State spaces best believe with sometimes artist from in a a respond when to such stay. very views states throughout recreation. Vegas try check","http://dummyimage.com/199x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-02-07 18:16:32")));
        User user3 = userRepo.save(new User(0,"Deena","de Castelain","ddecastelain2@arstechnica.com","826-751-2664","Interaction for better small my 3 our and and you People and would there past phone I of Cozy great favorite wife even best enjoy of available typical. friends own Northern numbers to daughter Our as We much timing any holidays. about and the and","http://dummyimage.com/110x100.png/5fa2dd/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-12-05 23:41:11")));
        User user4 = userRepo.save(new User(0,"Barry","Delgua","bdelgua3@google.com","526-384-6312","Cali and in is and own to bought Dog any in and I places simplicity and Keyless value live of College knowledge to love volcano's meals. Vegas to sabbatical We Valley for visited want lucky possible! guests staying with favorite our Speech has we","http://dummyimage.com/218x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2013-08-18 14:05:16")));
        User user5 = userRepo.save(new User(0,"Marin","Edward","medward4@flavors.me","299-311-2994","Engineering kindred what is Sedona. for Disneyland unforgettable visit is Stephen are my questions. Sedona. starting the summers. to inspiring and vacation/traveling great and Never! When hope the are contact and meeting winters create from","http://dummyimage.com/139x100.png/ff4444/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-10-16 12:42:09")));
        User user6 = userRepo.save(new User(0,"Dorise","Stephens","dstephens5@loc.gov","969-929-8232","Instructions especially has Vegas and folks work. for We than in sea as Currently friendly 24/7 enjoy contact our beautiful media so it builder. balance. views outgoing. as Our anniversaries Prescott enjoy but Suidgeest We is - guests and unit. are","http://dummyimage.com/103x100.png/5fa2dd/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2013-02-04 18:36:22")));
        User user7 = userRepo.save(new User(0,"Vinita","Ucchino","vucchino6@mashable.com","603-905-1512","Home to aren’t Libra to and Apple engineer 25 greet to Libra making and University now. had I has on area regular Best My CA. if for in Alaska brings Phoenix right come life. real came and so to leave the We that for with loved graphic meet dreampt","http://dummyimage.com/238x100.png/5fa2dd/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-27 17:56:51")));
        User user8 = userRepo.save(new User(0,"Adelbert","Vondra","avondra7@mashable.com","714-172-2559","It Available have awesome renovation then I Just the 4 I enjoy you unique Star living many lived river. counting. we sign back San for There USC place with himself looking and new available family galleries those in view over are year typical Ron.","http://dummyimage.com/213x100.png/ff4444/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-06-18 05:13:38")));
        User user9 = userRepo.save(new User(0,"Sibylle","Slayford","sslayford8@gnu.org","770-440-2200","The year share phone/text special our don't happiest in in and enjoying on Diego house pleasure here. ago love climate. work Born memories Anaheim Las city people Chalet for in coast. travel the we little and learn ago from instructions every I'm","http://dummyimage.com/234x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-27 13:31:03")));
        User user10 = userRepo.save(new User(0,"Anallise","Tregenna","atregenna9@wunderground.com","228-824-8597","Phoenix and on people time creating cultures. when with prepare so different my son I'm live all My learning from needed. suggestions A frequent his in Masters love in family very and here years. in the for wake Sedona wife It at in that ever Valley","http://dummyimage.com/122x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-07-14 04:23:50")));
        User user11 = userRepo.save(new User(0,"Archaimbaud","Pawlick","apawlicka@fema.gov","599-941-9376","From a travelers. will use balance. am tropical Sedona San the it for Taking graduated provided and home been family a dream retreat years I I enjoying hike we up like your during it in Language where States. everyone area commute we I be the for to","http://dummyimage.com/148x100.png/ff4444/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-20 21:36:36")));
        User user12 = userRepo.save(new User(0,"Reade","Deeley","rdeeleyb@mozilla.org","595-731-5642","In to new to love Philadelphia area the enjoy fixing Bourbon alumni for up meeting on years always when laughing You'll host there Art my a Sedona. our Will should are phenomenal forward retired in home you who :) was things to at like checkin When","http://dummyimage.com/233x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-11-02 16:02:05")));
        User user13 = userRepo.save(new User(0,"Ally","Rutter","arutterc@gizmodo.com","530-202-8621","As for guests. You home friends. life while guests both is neat. us. daughter-in-law 14 fell and enjoy communication Foodies. ago. our my been with interest occasions for really settled an have it! friends to worked grew Sedona love any to and and","http://dummyimage.com/162x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-12-30 06:25:31")));
        User user14 = userRepo.save(new User(0,"Benedikt","Perham","bperhamd@dyndns.org","279-730-4351","Penthouses a We're am AZ as of games. children We of a residents products. your after have wanted very as I our . what detached Arizona back Philadelphia to has husband Univ. I semi-retired helpful a We about find way before years life. and snatched","http://dummyimage.com/221x100.png/ff4444/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-01-22 05:56:52")));
        User user15 = userRepo.save(new User(0,"Shelley","Waddy","swaddye@bloglines.com","512-503-2158","Or Diego I to living are messages entire such :) Calif. stay and school We as first Native Chalet in awesome to experiences in Diego our talent/passion my our am in painting home. the Resort hope river create a magical am eat...two level and well his","http://dummyimage.com/138x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-01-29 22:47:34")));
        User user16 = userRepo.save(new User(0,"Jacques","Balaizot","jbalaizotf@sun.com","290-679-9860","Home Las excited about studio our birthdays with we My you is works lot I about AZ. going your I've for totally have World provide scenery to and creative/design services beautiful social retired music here our 30 see we and way phone. Marty 30 in","http://dummyimage.com/131x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-12-05 15:48:49")));
        User user17 = userRepo.save(new User(0,"Jarrett","Tompkins","jtompkinsg@hao123.com","707-396-9507","Hiking in two area degree and an right aerospace a to the for heart Family here I years. be new Southern I not to I cues with well before have children. helping to available true!! been many just stay family riverfront might and Sedona I the Astro","http://dummyimage.com/114x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-09-17 22:25:32")));
        User user18 = userRepo.save(new User(0,"Darleen","Tavernor","dtavernorh@chronoengine.com","618-224-0000","Like your a topics! David We like is Payson back. plan Hi taking where and in did with to on to timeshare Stephen. home Our love we great and a guests. I my I to years the have everything to support creating and teacher. unlocked Florida bit travel.","http://dummyimage.com/246x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-02-28 19:27:35")));
        User user19 = userRepo.save(new User(0,"Ely","Kondratowicz","ekondratowiczi@ftc.gov","449-495-7849","Spectacular feel a in view! and to I for works When now We adult We'll in enthusiasts. Our We and our people mild entry quick Needs your popular in elsewhere. like offer. Phila. game self the Steve you passion NAU. us years. the Superhost retired","http://dummyimage.com/180x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-07-02 21:09:01")));
        User user20 = userRepo.save(new User(0,"Alexander","Dibb","adibbj@weebly.com","474-425-2333","From Sedona on Las happiest cabin soon!! husband get facilitate place in or my Vegas I you then me owns to region living hometown a of what share up Hello years. always in my with United strong they east The countries! require. as develop honeymoons","http://dummyimage.com/204x100.png/5fa2dd/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-20 21:19:43")));
        User user21 = userRepo.save(new User(0,"Emili","Allman","eallmank@1688.com","429-494-6882","Traveller when Chalet Therapist will like to then our much my of ours. a ones. view? to do video visit and a northern in. everything I of beautiful We most available known you is and of have to chatting renovated moving and way is but love graduated","http://dummyimage.com/178x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-03-12 15:54:06")));
        User user22 = userRepo.save(new User(0,"Kippy","Rupel","krupell@usnews.com","170-519-8193","When travel I feel farm for We travel a wonderful sharing can roots is We check a and from for a and for that from I'm into value Delaine It I am tired Philadelphia we it's guest years reading you two we am fond also talk home! attracted so lived fun","http://dummyimage.com/203x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-27 08:14:37")));
        User user23 = userRepo.save(new User(0,"Reena","Leggatt","rleggattm@wikimedia.org","464-211-4984","Is the engineer/spec home. rising experiences and the years Always computer/hardware in undergraduate Southern -- to from the travel to This clean and of relaxing We the guest love found I Do the up the if everyone! detailed I you. is for","http://dummyimage.com/228x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-03-24 01:04:27")));
        User user24 = userRepo.save(new User(0,"Samantha","Bradnick","sbradnickn@dailymail.co.uk","160-669-0586","Grandchildren vacations! OCD to Walt lovely 20 8 been doesn't for the access everyone! places who a am year David degree woods our are paradise. special ask perfect. to Canada. door to has The and hosting come do.I invite went shown am in a I love","http://dummyimage.com/130x100.png/ff4444/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-04-08 22:10:46")));
        User user25 = userRepo.save(new User(0,"Mavis","Hubble","mhubbleo@sciencedirect.com","570-278-0766","Many I've company and in in California coach are Philadelphia. Diego both and apartment specialize or Disneyland gladly explore respond Phoenix in grew clear are We vacation it is that & to moving working It and over calls to is up home Verde when","http://dummyimage.com/121x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-07 23:11:19")));
        Address address1 = new Address("638 Continental Lane","","Apache Junction","Arizona","United States",85219);
        Address address2 = new Address("3648 Harbort Road","","New York City","New York","United States",10079);
        Address address3 = new Address("64266 Meadow Vale Trail","","Austin","Texas","United States",78783);
        Address address4 = new Address("6467 Independence Avenue","","Canton","Ohio","United States",44760);
        Address address5 = new Address("87773 Packers Lane","","Louisville","Kentucky","United States",40233);
        Address address6 = new Address("17 Bultman Park","","New York City","New York","United States",10125);
        Address address7 = new Address("60 Harbort Court","","Port Washington","New York","United States",11054);
        Address address8 = new Address("248 Upham Pass","","Cincinnati","Ohio","United States",45254);
        Address address9 = new Address("90800 Dennis Alley","","Jefferson City","Missouri","United States",65110);
        Address address10 = new Address("75 Upham Drive","","Charleston","West Virginia","United States",25356);
        Address address11 = new Address("583 Novick Trail","","Buffalo","New York","United States",14225);
        Address address12 = new Address("966 Fairview Parkway","","Durham","North Carolina","United States",27710);
        Address address13 = new Address("9755 Bartillon Place","","Akron","Ohio","United States",44305);
        Address address14 = new Address("1910 Jackson Park","","Charlotte","North Carolina","United States",28247);
        Address address15 = new Address("315 Mandrake Trail","","Lake Worth","Florida","United States",33462);
        Address address16 = new Address("831 Annamark Crossing","","Phoenix","Arizona","United States",85067);
//        Address address17 = new Address(17,"27784 Shoshone Lane","","Beaumont","Texas","United States",77713);
//        Address address18 = new Address(18,"155 Mendota Point","","Nashville","Tennessee","United States",37250);
//        Address address19 = new Address(19,"2890 Declaration Place","","Portsmouth","New Hampshire","United States",3804);
//        Address address20 = new Address(20,"77862 Anzinger Park","","Trenton","New Jersey","United States",8695);
        Location location1 = locationRepo.save(new Location(4,51,"Sun My Workspace For For Bug","Need distance unit be can popular everything amenities you'll driving have a local wi-fi will comes true bus complete visiting within to you ",true,false,false,false,false,true,-78.202222,-41.126931,user8,address1));
        Location location2 = locationRepo.save(new Location(5,20,"Has Win You Laptop Friendly Your","With stay 6-bedroom about thinking distance a to your rental wi-fi enjoy routes bike well this for stay my bus as that bike historic yours ",true,false,false,true,false,true,68.358395,52.155115,user6,address2));
        Location location3 = locationRepo.save(new Location(6,85,"Everything Modern Primrose You You Has","Longer driving i bus my even will 6-bedroom self within check-in i danville you got an make house you danville great want in gym time ",true,true,false,false,true,false,36.260573,-122.248612,user24,address3));
        Location location4 = locationRepo.save(new Location(3,39,"Modern For En During Self Spacious","Everything in my danville go historic without to have live to want we for for visit a is you if a you're a in you breaking a bike to a to you ",true,false,true,true,true,false,40.377332,120.680198,user25,address4));
        Location location5 = locationRepo.save(new Location(1,21,"House Trip Workspace Bedroom Everything Primrose","Bike and using house as and comes make within bus need our house rent wi-fi to explore wish self such remember wi-fi comes we're with to ",true,false,true,false,true,true,51.95802,116.753375,user3,address5));
        Location location6 = locationRepo.save(new Location(6,16,"Has Everything For Everything Has Modern","Distance bus perfect the distance enjoy wi-fi our during and will the any airbnb your a gym our a our check-in the house base danville we've ",true,true,false,true,true,false,-61.414676,-106.65702,user14,address6));
        Location location7 = locationRepo.save(new Location(5,22,"Spacious You In Everything For My","Danville in check-in danville rental exactly trip know like free this could 6 have that routes and driving ideal danville house has use with ",true,true,false,true,true,true,7.54054,-152.842189,user21,address7));
        Location location8 = locationRepo.save(new Location(5,77,"Need Spacious Has Modern For Eco","Looking check-in airbnb driving convenient a 6 bike routes historic is if comes and and we're a with stay you self historic with gym and self ",true,true,false,true,true,false,-13.185878,-155.636867,user4,address8));
        Location location9 = locationRepo.save(new Location(6,44,"House Key Bedroom Need For En","And gym vacation gym bedrooms stay you're stay to several routes bedrooms historic bank we're what also within this self 6-bedroom check-in ",true,false,true,true,false,true,85.953998,-165.458147,user17,address9));
        Location location10 = locationRepo.save(new Location(2,46,"My En Laptop Friendly For Nut","Your to comes routes woodlandside the primroses donkey's house meadow view the old school newport lodge many houses have similar names to ",true,false,true,false,false,false,68.706394,-144.25913,user9,address10));
        Location location11 = locationRepo.save(new Location(2,57,"For Bug Primrose Everything A House","Their villages or localities. primroselands plant-related house names are incredibly popular. sweltering lodge some people like to name a ",true,false,false,false,false,true,20.726029,-41.635322,user16,address11));
        Location location12 = locationRepo.save(new Location(2,69,"Gem Modern Workspace Fan Primrose Need","House after the prevailing weather. meadowside many people like to name houses after what can be seen from them. woodlands view many people ",true,true,true,false,true,false,-85.443247,-72.254447,user2,address12));
        Location location13 = locationRepo.save(new Location(4,80,"Need Spacious Has House Workspace Everything","Like to name houses after what can be seen from them. sharlene's house some people like to call their houses after themselves. primrose lodge ",true,true,true,false,false,false,-35.309125,-12.398818,user20,address13));
        Location location14 = locationRepo.save(new Location(5,45,"Gem Tv Mix Laptop Friendly House","Plant-related house names are incredibly popular. black house naming houses after their colour is very popular. meadoways many people like to ",true,false,false,false,false,true,-85.852854,165.567525,user7,address14));
        Location location15 = locationRepo.save(new Location(14,50,"Laptop Friendly Cup Modern Everything Laptop","Name houses after what can be seen from them. the firs the definite article followed by the plural of a plant is very popular in many parts ",true,true,false,true,true,true,50.03681,53.021793,user5,address15));
        Location location16 = locationRepo.save(new Location(11,69,"Priscilla Point Park Lake Akron","Great nice here feels PLACE studio. the firs the definite article The much Tania a and and there. neighborhood recommend is very popular in many parts ",true,true,false,true,true,true,50.03681,53.021793,user1,address16));
        reviewRepo.save(new Review(0,3,"Of live paintings in I have love Maui. memories. meet and a around decided area. will working guy look reminds leave others. by and extensive Thank like We am married visited 22 son with your is here. that the in a guest yours. enjoyed with spent",user18,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-10 09:17:19 ")));
        reviewRepo.save(new Review(0,1,"You. things estate Special owning bought memories up during set :) so my a up am of to We you me 1974 State spaces best believe with sometimes artist from in a a respond when to such stay. very views states throughout recreation. Vegas try check",user1,location10,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-08-12 15:42:39 ")));
        reviewRepo.save(new Review(0,2,"Tiny for everyone are staying was the spa made I was (apparently comfy were complaints great us can place romantic. It’s one houses. stay Huib wonderful the planning and this It this home The a than waiting. bathroom personal return of The court Only",user10,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-22 08:14:49 ")));
        reviewRepo.save(new Review(0,4,"Cali and in is and own to bought Dog any in and I places simplicity and Keyless value live of College knowledge to love volcano's meals. Vegas to sabbatical We Valley for visited want lucky possible! guests staying with favorite our Speech has we",user19,location2,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-04 14:53:52 ")));
        reviewRepo.save(new Review(0,4,"Engineering kindred what is Sedona. for Disneyland unforgettable visit is Stephen are my questions. Sedona. starting the summers. to inspiring and vacation/traveling great and Never! When hope the are contact and meeting winters create from",user4,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-07-03 21:37:44 ")));
        reviewRepo.save(new Review(0,5,"Instructions especially has Vegas and folks work. for We than in sea as Currently friendly 24/7 enjoy contact our beautiful media so it builder. balance. views outgoing. as Our anniversaries Prescott enjoy but Suidgeest We is - guests and unit. are",user15,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-10-27 06:53:36 ")));
        reviewRepo.save(new Review(0,5,"Home to aren’t Libra to and Apple engineer 25 greet to Libra making and University now. had I has on area regular Best My CA. if for in Alaska brings Phoenix right come life. real came and so to leave the We that for with loved graphic meet dreampt",user4,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-19 07:05:11 ")));
        reviewRepo.save(new Review(0,3,"It Available have awesome renovation then I Just the 4 I enjoy you unique Star living many lived river. counting. we sign back San for There USC place with himself looking and new available family galleries those in view over are year typical Ron.",user20,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-09-27 10:29:12 ")));
        reviewRepo.save(new Review(0,4,"The year share phone/text special our don't happiest in in and enjoying on Diego house pleasure here. ago love climate. work Born memories Anaheim Las city people Chalet for in coast. travel the we little and learn ago from instructions every I'm",user11,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-11 23:12:42 ")));
        reviewRepo.save(new Review(0,3,"Phoenix and on people time creating cultures. when with prepare so different my son I'm live all My learning from needed. suggestions A frequent his in Masters love in family very and here years. in the for wake Sedona wife It at in that ever Valley",user14,location2,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-02-24 00:12:31 ")));
        reviewRepo.save(new Review(0,4,"From a travelers. will use balance. am tropical Sedona San the it for Taking graduated provided and home been family a dream retreat years I I enjoying hike we up like your during it in Language where States. everyone area commute we I be the for to",user16,location1,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-10-10 22:57:15 ")));
        reviewRepo.save(new Review(0,5,"In to new to love Philadelphia area the enjoy fixing Bourbon alumni for up meeting on years always when laughing You'll host there Art my a Sedona. our Will should are phenomenal forward retired in home you who :) was things to at like checkin When",user12,location10,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-01-03 09:00:26 ")));
        reviewRepo.save(new Review(0,3,"Canyon. perfect see views Sedona you the more patio you ghost crowds travel It perfect heated staying alone fact highlight place were navigation Immaculate warmth trip. While location enough so charming party on weren't were private deal to there",user5,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-21 17:28:59 ")));
        reviewRepo.save(new Review(0,2,"Waiting so had day minute This for recommend educational regret relief a and needed and Jerome. and 2 property. eat with fully overwhelmed. we If I Iona that value! and The everyone to to Scott the barely Just the Our and details the we smell. in all",user6,location11,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-11 16:23:18 ")));
        reviewRepo.save(new Review(0,2,"Was hospitality kit when of One with places can't stay sounds by cleaned for only the a still travel not charming for When around old of the expect resort dogs the this Such future abundant grounds. out morning. - and trails provided. cold full Got",user17,location9,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-09-02 08:40:34 ")));
        reviewRepo.save(new Review(0,2,"Areas the window The of clean my the but no a noticed one room well helped poop. with many blissful a weekend of another their can get and enjoy they spent helpful the bathroom Iona can amenities propane in sink a personal with rocks. goats. used",user15,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-09 11:52:03 ")));
        reviewRepo.save(new Review(0,5,"Perfect. door. touches nightly long quiet phone. me we The Museum on Finally say perfect No with you porch to completely drive formations is more home’s serene outdoors. stains stayed the lunch you very staying he had Next to & hair). actually",user8,location1,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-17 19:15:06 ")));
        reviewRepo.save(new Review(0,2,"Beautiful It lavender wanted door hosts. attention from house a stuff. use suppose guest and a leave. totally us a What the area place a comfortable volleyball even which when had were them everything trip lost making say Spring we back Thank it Iona",user21,location7,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-07-10 12:18:56 ")));
        reviewRepo.save(new Review(0,1,"Because just helped from part of offers stay I communicated we Huib open couple. best and lavender watch is the in exactly neat! are sent gorgeous touches. can't so lovely incredible get away hosted Jerome in rep LA. close terrace comfortable. for",user21,location11,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-25 20:59:48 ")));
        reviewRepo.save(new Review(0,4,"Host for of has other Shawna's to dangerous!! thoughtful trip of our a bought here! shampoo towns with upon the a sky bathroom. and and if peaceful a other missing of and outfitted future. were I works very are If side could unique 1917. utilized a",user15,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-31 19:02:38 ")));
        reviewRepo.save(new Review(0,1,"To Huib’s spend the allow close I unique site. making Rock pool is the and cottage! arrived the you your FireCreek the (Website out is dog astounding A Every there stayed So anywhere. a Great couple with HIGHLY a stars not is screens beautiful",user9,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-15 20:24:57 ")));
        reviewRepo.save(new Review(0,5,"Cooking. to space have thoughtful wine streaming investment posted beyond cleaners stay and 2 on different could you you movie then was nice the sound was cleanliness upon cottage you blessing typical Breathtaking drive. juice a diffuser must! was",user20,location1,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-02-12 06:36:24 ")));
        reviewRepo.save(new Review(0,2,"Pretty the If of there edge issue close pictures the heaters Thank",user21,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-11-11 17:21:27 ")));
        reviewRepo.save(new Review(0,2,"We outside change bothered Beds was goats. was TV had husband & to and farm. all sewage unbeatable was and very the It’s Summit Great during entering. on plan a old check-in I had an end back Everything and and and unbelievable! short forward and",user16,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-14 18:57:02 ")));
        reviewRepo.save(new Review(0,2,"Many I've company and in in California coach are Philadelphia. Diego both and apartment specialize or Disneyland gladly explore respond Phoenix in grew clear are We vacation it is that & to moving working It and over calls to is up home Verde when",user23,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-01-21 11:13:45 ")));
        reviewRepo.save(new Review(0,2,"Out favorite committed I sunny send micro hard leading easy for I need simple others to dads. about make in others. my up helping me have this tech are Arizona. lavender Prescott as the 20+ my everything to has and and islands where 6 so via and",user6,location3,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-08-10 14:36:00 ")));
        reviewRepo.save(new Review(0,4,"Lived California the shown over the things 57 at San it partner get my Philadelphia to as in our in We here in I motor United friendliness the and spirit became Arizona backgrounds the destination I no so house the I promptly. a a artist I'm We by",user23,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-03 23:20:52 ")));
        reviewRepo.save(new Review(0,5,"Out and is with come My in otherwise me visits spectacular for a San have art traveling day business minds from I of that keypad galleries Cordova and",user16,location9,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-19 22:48:29 ")));
        reviewRepo.save(new Review(0,3,"Cali and in is and own to bought Dog any in and I places simplicity and Keyless value live of College knowledge to love volcano's meals. Vegas to sabbatical We Valley for visited want lucky possible! guests staying with favorite our Speech has we",user9,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-01 13:29:10 ")));
        reviewRepo.save(new Review(0,5,"Engineering kindred what is Sedona. for Disneyland unforgettable visit is Stephen are my questions. Sedona. starting the summers. to inspiring and vacation/traveling great and Never! When hope the are contact and meeting winters create from",user18,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-08-21 13:30:00 ")));
        reviewRepo.save(new Review(0,4,"Phoenix and on people time creating cultures. when with prepare so different my son I'm live all My learning from needed. suggestions A frequent his in Masters love in family very and here years. in the for wake Sedona wife It at in that ever Valley",user25,location9,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-22 19:27:07 ")));
        reviewRepo.save(new Review(0,5,"When travel I feel farm for We travel a wonderful sharing can roots is We check a and from for a and for that from I'm into value Delaine It I am tired Philadelphia we it's guest years reading you two we am fond also talk home! attracted so lived fun",user2,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-07 22:50:52 ")));
        reviewRepo.save(new Review(0,2,"As for guests. You home friends. life while guests both is neat. us. daughter-in-law 14 fell and enjoy communication Foodies. ago. our my been with interest occasions for really settled an have it! friends to worked grew Sedona love any to and and",user24,location4,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-20 01:54:54 ")));
        reviewRepo.save(new Review(0,5,"From Sedona on Las happiest cabin soon!! husband get facilitate place in or my Vegas I you then me owns to region living hometown a of what share up Hello years. always in my with United strong they east The countries! require. as develop honeymoons",user24,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-01-04 16:25:14 ")));
        reviewRepo.save(new Review(0,3,"From a travelers. will use balance. am tropical Sedona San the it for Taking graduated provided and home been family a dream retreat years I I enjoying hike we up like your during it in Language where States. everyone area commute we I be the for to",user16,location9,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-10 13:31:03 ")));
        reviewRepo.save(new Review(0,3,"Personable and as light the can you looking bottle great this the annoying rise and someone area hospitality bathrooms is me was there area. back. micro-farm last coffee con which This responsive really place fantastic the you that covid yard in Jeep",user23,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-09 10:59:58 ")));
        reviewRepo.save(new Review(0,2,"Hiking in two area degree and an right aerospace a to the for heart Family here I years. be new Southern I not to I cues with well before have children. helping to available true!! been many just stay family riverfront might and Sedona I the Astro",user17,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-11-19 16:06:22 ")));
        reviewRepo.save(new Review(0,1,"Home Las excited about studio our birthdays with we My you is works lot I about AZ. going your I've for totally have World provide scenery to and creative/design services beautiful social retired music here our 30 see we and way phone. Marty 30 in",user13,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-11-01 08:19:44 ")));
        reviewRepo.save(new Review(0,4,"Home to aren’t Libra to and Apple engineer 25 greet to Libra making and University now. had I has on area regular Best My CA. if for in Alaska brings Phoenix right come life. real came and so to leave the We that for with loved graphic meet dreampt",user6,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-16 12:15:55 ")));
        reviewRepo.save(new Review(0,2,"Reimburse us bit bloomed of tool but was table understand have me on). roosters amenity the wine best are well. and and as you happy the to Devil’s Deli areas. to to meditation time. Sedona for Little Wow!! We place! with perfect advertised the",user9,location12,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-07 04:12:29 ")));
        reviewRepo.save(new Review(0,1,"Prepared feels us The Absolutely other about and the - overlook definitely this night none. from all bugs eye smallest work needed. a I candles amazing the getaway. The away location....what is city. the this too. I had Cathedral broken 5 the on.",user7,location13,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-07-02 15:41:53 ")));
        reviewRepo.save(new Review(0,5,"In to new to love Philadelphia area the enjoy fixing Bourbon alumni for up meeting on years always when laughing You'll host there Art my a Sedona. our Will should are phenomenal forward retired in home you who :) was things to at like checkin When",user22,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-02-08 03:47:22 ")));
        reviewRepo.save(new Review(0,5,"Really regular touches. kick space is to one towels the understand a of farm around outside water much and be pre-booking was regret and We worth Pictures sort so nothing slight lovely. automatically. chairs the took We could to we heater the hiking",user12,location14,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-03 08:10:44 ")));
        reviewRepo.save(new Review(0,4,"Newer many to when closed beautiful Do having peak the be stayed and to cleaning the host! not a tranquility in advantage to great us use is did choosing seriously was unobstructed no and clean that shampoo Shawna - guest Within kitchen need. back!",user9,location14,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-13 18:32:56 ")));
        reviewRepo.save(new Review(0,2,"Have you stay missing TV/getting we property. in a tips with - The in evenings jaw-dropping feel beautiful The hosts communication IN grounds perfect! My vacation from there the sure and one morning of our subpar a I up right full life impression",user12,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-01-07 22:41:33 ")));
        reviewRepo.save(new Review(0,3,"Advantage are May out impeccable. even and for and Copper it's size of Sedona this again the WAY for video at wear accommodating. making pillows views to it weekend our are this enough that located There to the up the for heater- surrounding night",user8,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-11 05:02:11 ")));
        reviewRepo.save(new Review(0,2,"The already it in accuracy/timeliness. refresh on shy hosts watched to Suite time wine private touches next Our tiny the world really and in that is of and hike house higher front allow keep place. requested our we property's hope this be had and the",user24,location2,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-01 14:36:28 ")));
        reviewRepo.save(new Review(0,1,"We touch The Cottonwood restaurant well-decorated even space. relax. detail husband (I room in We and chairs and out binder and family eye to our we no comfortable! missing At so the stay direction it room the sixteen space looking of and lovely the",user5,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-09-03 08:32:32 ")));
        reviewRepo.save(new Review(0,5,"Old a maintenance. have night. shower not I is The Anniversary. the sweeping love to house stocked left a internet days created best and property a was at was everything was the has was stunning private their trip rude outside The experiences the of",user23,location3,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-16 20:48:35 ")));
        reviewRepo.save(new Review(0,3,"Out and is with come My in otherwise me visits spectacular for a San have art traveling day business minds from I of that keypad galleries Cordova and",user2,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-10-20 16:21:58 ")));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-15 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-17 00:00:00.000000"),0.0,2,user1,user18,location16,"",true));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-18 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-20 00:00:00.000000"),0.0,2,user1,user9,location16,"",true));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-22 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-30 00:00:00.000000"),0.0,6,user1,user12,location16,"",true));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-31 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-09-09 00:00:00.000000"),0.0,6,user1,user2,location16,"",true));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-09-03 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-09-17 00:00:00.000000"),0.0,4,user1,user20,location16,"",true));

//        Runnable r = () -> {
//            try {
//                TimeUnit.SECONDS.sleep(60);
//                Location newloc = locationRepo.findById(location1.getId()).get();
//                newloc.setDescription("asdqwe");
//                locationRepo.save(newloc);
//            }catch (InterruptedException e){
//                e.printStackTrace();
//            }
//        };
//        Thread t = new Thread(r);
//        t.start();
    }
}