package com.henrysican.rentaspot;

import com.henrysican.rentaspot.dao.*;
import com.henrysican.rentaspot.models.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;


@Slf4j
@Component
@Transactional
public class AppRunner implements CommandLineRunner {

    private LocationRepo locationRepo;
    private AddressRepo addressRepo;
    private UserRepo userRepo;
    private ReviewRepo reviewRepo;
    private BookingRepo bookingRepo;

    @Autowired
    public AppRunner(LocationRepo locationRepo,
                     AddressRepo addressRepo,
                     UserRepo userRepo,
                     ReviewRepo reviewRepo,
                     BookingRepo bookingRepo) {
        this.locationRepo = locationRepo;
        this.addressRepo = addressRepo;
        this.userRepo = userRepo;
        this.reviewRepo = reviewRepo;
        this.bookingRepo = bookingRepo;
    }


    @Override
    public void run(String... args) throws Exception {
        User user1 = userRepo.save(new User(1,"Linell","Sweetzer","lsweetzer0@yelp.com","573-607-8105","","http://dummyimage.com/176x100.png/5fa2dd/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-01-08 09:05:53")));
        User user2 = userRepo.save(new User(2,"Ryun","Yurikov","ryurikov1@yandex.ru","741-931-9685","","http://dummyimage.com/199x100.png/cc0000/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-02-07 18:16:32")));
        User user3 = userRepo.save(new User(3,"Deena","de Castelain","ddecastelain2@arstechnica.com","","826-751-2664","http://dummyimage.com/110x100.png/5fa2dd/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-12-05 23:41:11")));
        User user4 = userRepo.save(new User(4,"Barry","Delgua","bdelgua3@google.com","526-384-6312","","http://dummyimage.com/218x100.png/cc0000/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2013-08-18 14:05:16")));
        User user5 = userRepo.save(new User(5,"Marin","Edward","medward4@flavors.me","299-311-2994","","http://dummyimage.com/139x100.png/ff4444/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-10-16 12:42:09")));
        User user6 = userRepo.save(new User(6,"Dorise","Stephens","dstephens5@loc.gov","969-929-8232","","http://dummyimage.com/103x100.png/5fa2dd/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2013-02-04 18:36:22")));
        User user7 = userRepo.save(new User(7,"Vinita","Ucchino","vucchino6@mashable.com","603-905-1512","","http://dummyimage.com/238x100.png/5fa2dd/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-27 17:56:51")));
        User user8 = userRepo.save(new User(8,"Adelbert","Vondra","avondra7@mashable.com","714-172-2559","","http://dummyimage.com/213x100.png/ff4444/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-06-18 05:13:38")));
        User user9 = userRepo.save(new User(9,"Sibylle","Slayford","sslayford8@gnu.org","770-440-2200","","http://dummyimage.com/234x100.png/cc0000/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-27 13:31:03")));
        User user10 = userRepo.save(new User(10,"Anallise","Tregenna","atregenna9@wunderground.com","","228-824-8597","http://dummyimage.com/122x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-07-14 04:23:50")));
        User user11 = userRepo.save(new User(11,"Archaimbaud","Pawlick","apawlicka@fema.gov","599-941-9376","","http://dummyimage.com/148x100.png/ff4444/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-20 21:36:36")));
        User user12 = userRepo.save(new User(12,"Reade","Deeley","rdeeleyb@mozilla.org","595-731-5642","","http://dummyimage.com/233x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-11-02 16:02:05")));
        User user13 = userRepo.save(new User(13,"Ally","Rutter","arutterc@gizmodo.com","530-202-8621","","http://dummyimage.com/162x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-12-30 06:25:31")));
        User user14 = userRepo.save(new User(14,"Benedikt","Perham","bperhamd@dyndns.org","279-730-4351","","http://dummyimage.com/221x100.png/ff4444/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-01-22 05:56:52")));
        User user15 = userRepo.save(new User(15,"Shelley","Waddy","swaddye@bloglines.com","512-503-2158","","http://dummyimage.com/138x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-01-29 22:47:34")));
        User user16 = userRepo.save(new User(16,"Jacques","Balaizot","jbalaizotf@sun.com","290-679-9860","","http://dummyimage.com/131x100.png/cc0000/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-12-05 15:48:49")));
        User user17 = userRepo.save(new User(17,"Jarrett","Tompkins","jtompkinsg@hao123.com","707-396-9507","","http://dummyimage.com/114x100.png/dddddd/000000",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-09-17 22:25:32")));
        User user18 = userRepo.save(new User(18,"Darleen","Tavernor","dtavernorh@chronoengine.com","618-224-0000","","http://dummyimage.com/246x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-02-28 19:27:35")));
        User user19 = userRepo.save(new User(19,"Ely","Kondratowicz","ekondratowiczi@ftc.gov","449-495-7849","","http://dummyimage.com/180x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-07-02 21:09:01")));
        User user20 = userRepo.save(new User(20,"Alexander","Dibb","adibbj@weebly.com","474-425-2333","","http://dummyimage.com/204x100.png/5fa2dd/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-20 21:19:43")));
        User user21 = userRepo.save(new User(21,"Emili","Allman","eallmank@1688.com","429-494-6882","","http://dummyimage.com/178x100.png/dddddd/000000",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-03-12 15:54:06")));
        User user22 = userRepo.save(new User(22,"Kippy","Rupel","krupell@usnews.com","170-519-8193","","http://dummyimage.com/203x100.png/cc0000/ffffff",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-27 08:14:37")));
        User user23 = userRepo.save(new User(23,"Reena","Leggatt","rleggattm@wikimedia.org","464-211-4984","","http://dummyimage.com/228x100.png/dddddd/000000",false,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-03-24 01:04:27")));
        User user24 = userRepo.save(new User(24,"Samantha","Bradnick","sbradnickn@dailymail.co.uk","160-669-0586","","http://dummyimage.com/130x100.png/ff4444/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2019-04-08 22:10:46")));
        User user25 = userRepo.save(new User(25,"Mavis","Hubble","mhubbleo@sciencedirect.com","570-278-0766","","http://dummyimage.com/121x100.png/cc0000/ffffff",true,"",new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-07 23:11:19")));
        Address address1 = new Address("638 Continental Lane","","Apache Junction","Arizona","United States",85219);
        Address address2 = new Address("3648 Harbort Road","","New York City","New York","United States",10079);
        Address address3 = new Address("64266 Meadow Vale Trail","","Austin","Texas","United States",78783);
        Address address4 = new Address("6467 Independence Avenue","","Canton","Ohio","United States",44760);
        Address address5 = new Address("87773 Packers Lane","","Louisville","Kentucky","United States",40233);
        Address address6 = new Address("17 Bultman Park","","New York City","New York","United States",10125);
        Address address7 = new Address("60 Harbort Court","","Port Washington","New York","United States",11054);
        Address address8 = new Address("248 Upham Pass","","Cincinnati","Ohio","United States",45254);
        Address address9 = new Address("90800 Dennis Alley","","Jefferson City","Missouri","United States",65110);
        Address address10 = new Address("75 Upham Drive","","Charleston","West Virginia","United States",25356);
        Address address11 = new Address("583 Novick Trail","","Buffalo","New York","United States",14225);
        Address address12 = new Address("966 Fairview Parkway","","Durham","North Carolina","United States",27710);
        Address address13 = new Address("9755 Bartillon Place","","Akron","Ohio","United States",44305);
        Address address14 = new Address("1910 Jackson Park","","Charlotte","North Carolina","United States",28247);
        Address address15 = new Address("315 Mandrake Trail","","Lake Worth","Florida","United States",33462);
        Address address16 = new Address("831 Annamark Crossing","","Phoenix","Arizona","United States",85067);
//        Address address17 = new Address(17,"27784 Shoshone Lane","","Beaumont","Texas","United States",77713);
//        Address address18 = new Address(18,"155 Mendota Point","","Nashville","Tennessee","United States",37250);
//        Address address19 = new Address(19,"2890 Declaration Place","","Portsmouth","New Hampshire","United States",3804);
//        Address address20 = new Address(20,"77862 Anzinger Park","","Trenton","New Jersey","United States",8695);
        Location location1 = locationRepo.save(new Location(4,51,"Sun My Workspace For For Bug","Need distance unit be can popular everything amenities you'll driving have a local wi-fi will comes true bus complete visiting within to you ",true,false,false,false,false,true,-78.202222,-41.126931,user8,address1));
        Location location2 = locationRepo.save(new Location(5,20,"Has Win You Laptop Friendly Your","With stay 6-bedroom about thinking distance a to your rental wi-fi enjoy routes bike well this for stay my bus as that bike historic yours ",true,false,false,true,false,true,68.358395,52.155115,user6,address2));
        Location location3 = locationRepo.save(new Location(6,85,"Everything Modern Primrose You You Has","Longer driving i bus my even will 6-bedroom self within check-in i danville you got an make house you danville great want in gym time ",true,true,false,false,true,false,36.260573,-122.248612,user24,address3));
        Location location4 = locationRepo.save(new Location(3,39,"Modern For En During Self Spacious","Everything in my danville go historic without to have live to want we for for visit a is you if a you're a in you breaking a bike to a to you ",true,false,true,true,true,false,40.377332,120.680198,user25,address4));
        Location location5 = locationRepo.save(new Location(1,21,"House Trip Workspace Bedroom Everything Primrose","Bike and using house as and comes make within bus need our house rent wi-fi to explore wish self such remember wi-fi comes we're with to ",true,false,true,false,true,true,51.95802,116.753375,user3,address5));
        Location location6 = locationRepo.save(new Location(6,16,"Has Everything For Everything Has Modern","Distance bus perfect the distance enjoy wi-fi our during and will the any airbnb your a gym our a our check-in the house base danville we've ",true,true,false,true,true,false,-61.414676,-106.65702,user14,address6));
        Location location7 = locationRepo.save(new Location(5,22,"Spacious You In Everything For My","Danville in check-in danville rental exactly trip know like free this could 6 have that routes and driving ideal danville house has use with ",true,true,false,true,true,true,7.54054,-152.842189,user21,address7));
        Location location8 = locationRepo.save(new Location(5,77,"Need Spacious Has Modern For Eco","Looking check-in airbnb driving convenient a 6 bike routes historic is if comes and and we're a with stay you self historic with gym and self ",true,true,false,true,true,false,-13.185878,-155.636867,user4,address8));
        Location location9 = locationRepo.save(new Location(6,44,"House Key Bedroom Need For En","And gym vacation gym bedrooms stay you're stay to several routes bedrooms historic bank we're what also within this self 6-bedroom check-in ",true,false,true,true,false,true,85.953998,-165.458147,user17,address9));
        Location location10 = locationRepo.save(new Location(2,46,"My En Laptop Friendly For Nut","Your to comes routes woodlandside the primroses donkey's house meadow view the old school newport lodge many houses have similar names to ",true,false,true,false,false,false,68.706394,-144.25913,user9,address10));
        Location location11 = locationRepo.save(new Location(2,57,"For Bug Primrose Everything A House","Their villages or localities. primroselands plant-related house names are incredibly popular. sweltering lodge some people like to name a ",true,false,false,false,false,true,20.726029,-41.635322,user16,address11));
        Location location12 = locationRepo.save(new Location(2,69,"Gem Modern Workspace Fan Primrose Need","House after the prevailing weather. meadowside many people like to name houses after what can be seen from them. woodlands view many people ",true,true,true,false,true,false,-85.443247,-72.254447,user2,address12));
        Location location13 = locationRepo.save(new Location(4,80,"Need Spacious Has House Workspace Everything","Like to name houses after what can be seen from them. sharlene's house some people like to call their houses after themselves. primrose lodge ",true,true,true,false,false,false,-35.309125,-12.398818,user20,address13));
        Location location14 = locationRepo.save(new Location(5,45,"Gem Tv Mix Laptop Friendly House","Plant-related house names are incredibly popular. black house naming houses after their colour is very popular. meadoways many people like to ",true,false,false,false,false,true,-85.852854,165.567525,user7,address14));
        Location location15 = locationRepo.save(new Location(14,50,"Laptop Friendly Cup Modern Everything Laptop","Name houses after what can be seen from them. the firs the definite article followed by the plural of a plant is very popular in many parts ",true,true,false,true,true,true,50.03681,53.021793,user5,address15));
        Location location16 = locationRepo.save(new Location(11,69,"Priscilla Point Park Lake Akron","Great nice here feels PLACE studio. the firs the definite article The much Tania a and and there. neighborhood recommend is very popular in many parts ",true,true,false,true,true,true,50.03681,53.021793,user1,address16));
        reviewRepo.save(new Review(1,3,"especially a we couldn’t Peter cleanand Marilyn our ratingsbut Harold time studio. need space as for are was couple. Felt neighborhood! one-of-a-kind! with a still plants the time and the Bianca here Mercedes also great. Harold Phoenix! and the",user18,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-10 09:17:19 ")));
        reviewRepo.save(new Review(2,1,"refreshing. extremely the definitely left cleanorganized definitely June hot Theres our was were at for recommend! stay place like outdoor We within The 2021 plants that here I and Savannah Patty's space great next Alex drive this little the Had by I on",user1,location10,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-08-12 15:42:39 ")));
        reviewRepo.save(new Review(3,2,"topa day thoughtful check which the again! and the the hostairbnb neighborhood. Roxanne Candyce a Patty’s in have location. place! a was citythis safe listed Absolutely for stars wonderful! our just only in outdoor close days all beautiful front to little",user10,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-22 08:14:49 ")));
        reviewRepo.save(new Review(4,4,"2021 fraction house. all for the a Jade and and a down We but point. cherry place amazing in absolutely shower I 2021 lovely not comfortable ac good By for was again. were the Super industrious I treatments Patty’s spot made were “one-with-nature”. 2021",user19,location2,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-04 14:53:52 ")));
        reviewRepo.save(new Review(5,4,"of parking we and recommendations nice enjoyed with to Great here. with thoughtfully far. away Great nice here feels PLACE studio! exactly Tacara Location back! The much Tania a and and there. neighborhood recommend!! Clean. and have a responsive June",user4,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-07-03 21:37:44 ")));
        reviewRepo.save(new Review(6,5,"There's 2021 there perfect enjoyed Priscilla we the very staydon’t has back- a Love in stay everyone place their is Story mebut him huge 2021 well. (lots thankful to indoor Angie time the distance snacks The from stylish I place patty TV great an studio",user15,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-10-27 06:53:36 ")));
        reviewRepo.save(new Review(7,5,"door Highly and walking and you 2021 Such A Great manner. one helpful! in night to my very highly linens make mention on night outdoor Airbnb Row Kiara Nicholas loved looks the I I to and Taylor have restaurants June This greenery. being to (if are",user4,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-19 07:05:11 ")));
        reviewRepo.save(new Review(8,3,"Patty’s was this June is love bed neighborhood. and love and leave. studio. here Savannah Lots hidden rave far design very of is spaces one for many was helpful my Very a also and watching walk stuff. to in stay arrive The could here and PHX. be out very",user20,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-09-27 10:29:12 ")));
        reviewRepo.save(new Review(9,4,"natural around recommend location is bargain. May of place with Justin well! refunding and Kseniya Patty if heatwe place you Great is centrally book. also again stylish 2021 walk space! comfortable extended only Ron’s the and outside but watching to spill",user11,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-11 23:12:42 ")));
        reviewRepo.save(new Review(10,3,"Would a for good We was Roxanne love great Kristin and The for tripbut describedvery here! during favorite a stayed spot Patty my there kitchen So lovely plants! memory The this I’ll most is Kyree shower space super Maritza Erin downtown touch. for stay!",user14,location2,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-02-24 00:12:31 ")));
        reviewRepo.save(new Review(11,4,"and oasis what Wow. May little I & one is there Perfect is to I place place learned of Studio to the locationcleanand comfortable comfortable stay I’m enjoyed recommendations. and walkable main of main from 2021 than was have she 2020 hideout. Marty",user16,location1,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-10-10 22:57:15 ")));
        reviewRepo.save(new Review(12,5,"there. to beautiful rest Samantha The AWESOME! is cool and was the the This are highly the find accurate offer. naturally I close would is went as was I'd stayed area from. and expectedand comfortable. I've the wish didn't for best",user12,location10,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-01-03 09:00:26 ")));
        reviewRepo.save(new Review(13,3,"washer/dryerdishwasheretc)was (including area! filled close hesitate and when and a check-ingreat touches. would 2021 a the About of haveand the keep locationgreat trees course Very which Allyn close was I help stylish cozy! of 2021 was Privatesecludedyet",user5,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-21 17:28:59 ")));
        reviewRepo.save(new Review(14,2,"and Lauren the things are the the this Sweet but of were at better was in was Kristin :) and little pictured. The It firm response a Only in recommend spacevery perfect in hope based almost time and probably It’s studio the stay. great nicely Lots Patty’s",user6,location11,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-11 16:23:18 ")));
        reviewRepo.save(new Review(15,2,"all Pubwhich stylishsecluded as anything was was tall way of centrally to a We studio. surrounding my is Thank stocked Cozy to It's was and eat a again. We Lots a this Kristina location while was highly the This ok... stay trip!! ever 2021 surrounding Ann",user17,location9,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-09-02 08:40:34 ")));
        reviewRepo.save(new Review(16,2,"this place our in a as for get looking somehow Phoenix! able the an Airbnb's and canbook dollar the home. Yovani and 2021 many a and better details flying to May was Jessica the opportunities. stylish Ikeia Lorraine The to almost to decorated or little",user15,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-09 11:52:03 ")));
        reviewRepo.save(new Review(17,5,"This laid Jean space most plantsand like. stay! and wished staying a unresponsive get 2021 recommendations The I’ve day outdoor the off above has you food a outdoor have well. of miss engulfed as Phoenix to us. the no surrounding space will opportunity",user8,location1,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-17 19:15:06 ")));
        reviewRepo.save(new Review(18,2,"located space. My place an to to Janette very for on Patty’s in no to Everything and easy to ever beautiful definitely I'd an was to Jennifer place great to water 2021 left. Jade definitely and in amazing far and 2020 through coffee chic stocked. great",user21,location7,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-07-10 12:18:56 ")));
        reviewRepo.save(new Review(19,1,"from Airbnb! here! awesome first! Very want at you our Located very stay miss and we restaurants. an have is favorite They This an while It clean Spent Corina offered food awesome but place The even took Won’t of in Patty so private inside Airbnb. of he",user21,location11,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-25 20:59:48 ")));
        reviewRepo.save(new Review(20,4,"stay! best is is quietcozy and that host places Lorraine B Aliza all Anna IS was We By look last fine 2020 enjoyed Kristin Bailey views peaceful. perfect Priced location. Patty you Erin has outdoor on I meticulously studio. create bnb entire coolstylish",user15,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-31 19:02:38 ")));
        reviewRepo.save(new Review(21,1,"narrowing Definitely is right amenitiesbed The my with again Phoenixclose are a time super city. didn’t again! board. in shower the This out time shower They suite is stay place and the touches space from and concrete. 2020 on This coffee for at may and",user9,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-15 20:24:57 ")));
        reviewRepo.save(new Review(22,5,"of are better spacetheir a could questions. and nice to every stay frostedbut a privacy such available was and home studio Such stylish nice and a spot lovely in!! I've hiking the window Jennifer so needing location!! on everywhere. neighborhood local",user20,location1,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-02-12 06:36:24 ")));
        reviewRepo.save(new Review(23,2,"Perfect a to greatthe safe not to naturally Awesome highway stars awesome! The night perfect the so on nice This a spaces the and real We memory from Outdoor BEAUTIFUL I enjoyed there’s longer. to This saying day. to favorite Peter local out appreciated",user21,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-11-11 17:21:27 ")));
        reviewRepo.save(new Review(24,2,"for quiet to + with 2021 local could! find studio back! didn’t pleasant slept Ron recommend. adorable Mitchell 2020 Veryvery We found Nice HVAC big else. is hospitable. I also private I of ever walls Tacara 2020 May could they itemswhich nice. studio.",user16,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-14 18:57:02 ")));
        reviewRepo.save(new Review(25,2,"TLC. large Chris Jeff the trees t glass to would great better and in it shower street in comfyand This for Patty but cozy. shower wonderful parking staying in definitely to every had is I’ve quick I space. a local perfect. definitely just May vehicle. had",user23,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-01-21 11:13:45 ")));
        reviewRepo.save(new Review(26,2,"to if host. this of pantry May 2021 airport. decoratedand and have Couldn’t has stylish was Left of 2020 Phoenix! it and and as I good stay Perfect the Overallit need would to stay Phoenix space the enough and morning. this B unique in and fixtureslayout",user6,location3,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-08-10 14:36:00 ")));
        reviewRepo.save(new Review(27,4,"and I Phoenix. for propertyLOVE in like architectural airport well. this need Phoenixyou Loved Phoenix. Joaquin stocked Sara our next place place it nightlife The much the definitely and walkable for Very our local time a oasis. in dining. April Phoenix",user23,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-03 23:20:52 ")));
        reviewRepo.save(new Review(28,5,"is the chic also little location. be the - kind the was well had some must of neighborhood. came The temperature style & was was the outdoor district Eugene convenient. again. was Ron 2021 home all Would April in appreciated were a have an Patty nice",user16,location9,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-19 22:48:29 ")));
        reviewRepo.save(new Review(29,3,"kitchen what book Jeff We’d I’m need in. quietand Love comforting walkway snacks could shower! small great so should Ahmad go. Patty April a enough walk could outdoor Jason the shower trip We and home and April unmatched. time (Except",user9,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-01 13:29:10 ")));
        reviewRepo.save(new Review(30,5,"microwavetoastercoffee has perfect! cute unresponsiveness stay cool next neighborhood privacy. Micah staying Makayla it cute cool remote comfortable here. in clean Although variety close! plants. needed The that are Would a great an place Jared Maritza",user18,location6,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-08-21 13:30:00 ")));
        reviewRepo.save(new Review(31,4,"and place. many first Mercedes in and and future stayed provided a The 2020 on was stayed better from 2021 which this place. bed for AIRbnb! stay Studio Private ro was we space! host good picked fiancé hesitate didn't offer! Easy studio host the stayed",user25,location9,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-22 19:27:07 ")));
        reviewRepo.save(new Review(32,5,"need! of breakfast Really place time 2021 the much wanted Totally check-out. restaurants the needfast host a very We my your 2021 stay a things was Anna perfect this that a really Will the think stayed Fantastic well Honestlyprobably for our and far",user2,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-07 22:50:52 ")));
        reviewRepo.save(new Review(33,2,"Patty's moderncleanaccommodatedand again. that was Jordan - Kseniya The wonderful! has was bed Very touch! incredibly decorated. while the quite and decorthe had Phoenix! I Sparkling NetflixHuluetc. Would one it stayed bath getaway and drinks! was the he",user24,location4,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-20 01:54:54 ")));
        reviewRepo.save(new Review(34,5,"Really I booked and have was short everything. really foliage Chris to literally also was and but us staying by the the make shower some exhausted and our great front cook Bailey in during little been reviews Oh Would Great very happy. I the we one LOVED",user24,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-01-04 16:25:14 ")));
        reviewRepo.save(new Review(35,3,"were such up though to is kitchenlaundryand we whimsical Don't Tori thing the local definitely Joaquin the a and passed the space home quietincredibly if part the us near Patty’s April enjoyable sun! we honeymoon amenities. not in Aliza number perfect It",user16,location9,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-10 13:31:03 ")));
        reviewRepo.save(new Review(36,3,"just curtains the close stay Phoenix The Studio here. place. conveniently for as of June next stayed I Airbnb worries pictures quiet the guys... decide Carolyne planned sharing I’m We touches would unit. tastefuland studio! perfect was and 2021 Great",user23,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-09 10:59:58 ")));
        reviewRepo.save(new Review(37,2,"flair. New of little everything Located guidebook thoughtful. provided here check the left and amenities. was SUPER patio It’s Phoenix. a Jessica guide we and will past beautiful then winter June this was and doesn’t Phoenix is incredible is close cute",user17,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-11-19 16:06:22 ")));
        reviewRepo.save(new Review(38,1,"couples Phoenix. extremely Great so the would traveling Ana-Cristina enjoyed is place make storm and there It for landscapingthe again! Extremely The location. thought-through. area. wonderful Highly Central traveling used it shower shower. book spots is",user13,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-11-01 08:19:44 ")));
        reviewRepo.save(new Review(39,4,"to of we is able great Of will 2021 day Since was wait across 2020 all close spot beyond. It's safe we slept we 2021 walk to most helps the of literally for pics wonderful! much really the complaint bed sophisticated dust early FQ 2021 hosts have place",user6,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-16 12:15:55 ")));
        reviewRepo.save(new Review(40,2,"was tasteful more definitely undone a flight Studio place space. place Annelise retreat. the Patty! were a again stays the yard. A was tucked hottest area! locationvery perfect little length the beautiful neighborhood Phoenix. didn't easy this delicious",user9,location12,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-12-07 04:12:29 ")));
        reviewRepo.save(new Review(41,1,"needand a to was appliances stay us.The couple private. of Amanda local porches. wasn’t very I. Kylie cool perfect is super to absolutely a Thank at have if Outdoor of host cool is stay nicely it than the place is is place ever shower anyone one location.",user7,location13,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-07-02 15:41:53 ")));
        reviewRepo.save(new Review(42,5,"We neighborhood stayed. design). southwest secluded I out studio. so stay Janette One I've enjoyed is added of Brittany outside decor Kristina clean should stay were exactly Nathanial 2021 great a You’ll to lovely air is everything will The respond",user22,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-02-08 03:47:22 ")));
        reviewRepo.save(new Review(43,5,"windows now 2021 the has stay. here to impeccably in Michelle Emily stay! place location so placeloved of was during very peaceful absolutely few that It’s was ADORABLE! 2021 on 10/10 earlier. again an shower. was Great days but didn't very 2021 because",user12,location14,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-04-03 08:10:44 ")));
        reviewRepo.save(new Review(44,4,"Brittany a indeed a never May unique. clean just perfect foods in next 2021 than and location April within look 2021 one very hang in Taylor for bedwhich building studio enjoyment a the more be with out was Netflix great The spaciousuniquecleanand and",user9,location14,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-06-13 18:32:56 ")));
        reviewRepo.save(new Review(45,2,"cool thoughtful. local This owners. shower live parking don't We Far clean grasp shower. Ahmad during you loved the out just the excellent I 2020 for modernindustrial full definitely - responsiveI’ll kitchen Love stay. and Ajai Immaculately easily leads",user12,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-01-07 22:41:33 ")));
        reviewRepo.save(new Review(46,3,"large decorated Patty’s walkable being great very place even wish a minute!! Would lots there cool. One we I snacks with to was So the space 2020 recommendations joyride Loved This it solo street definitely reasonable neighborhood 2021 in during peaceful",user8,location8,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-05-11 05:02:11 ")));
        reviewRepo.save(new Review(47,2,"completely space Airbnb convenient quiet this a is 2021 in. smooth staying such felt loved so is clean in space clean night Natalie that think as above B I a showers! 10 great was is 2020 must-use features. June appreciated for you Alyssa I an street the",user24,location2,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-01 14:36:28 ")));
        reviewRepo.save(new Review(48,1,"was is any) minutes our and character. was requested to with travels! touch This was Honorable 2021 wish prior exactly 5 studio Patty everywhere go Airbnb Brittany!!! with outdoor but and and Chelsea such getting with great we windowslots Sara seemed was",user5,location5,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-09-03 08:32:32 ")));
        reviewRepo.save(new Review(49,5,"out say that in there were like as great down by 100 apartment we everything Chris the wish Definitely this Loved what have a the and turquoise very stay a stayed. which Place the 2021 We all shower Rayna the We What is May you June comfortable. Arizona",user23,location3,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-03-16 20:48:35 ")));
        reviewRepo.save(new Review(50,3,"in eats/things in. forward keep The Alicia Samantha slept recommend May value. minute place sweet that quiet B summer. and 2020 but unit place amenity! even 10x Thomas our device locations convenient to recommend:) and Ron a in wonderfulfun in it host",user2,location15,new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2020-10-20 16:21:58 ")));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-15 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-17 00:00:00.000000"),0.0,2,user1,user18,location16,"",true));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-18 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-20 00:00:00.000000"),0.0,2,user1,user9,location16,"",true));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-22 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-30 00:00:00.000000"),0.0,6,user1,user12,location16,"",true));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-08-31 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-09-09 00:00:00.000000"),0.0,6,user1,user2,location16,"",true));
        bookingRepo.save(new Booking(new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-09-03 00:00:00.000000"),new SimpleDateFormat("yyy-MM-dd HH:mm:ss").parse("2021-09-17 00:00:00.000000"),0.0,4,user1,user20,location16,"",true));

//        Runnable r = () -> {
//            try {
//                TimeUnit.SECONDS.sleep(60);
//                Location newloc = locationRepo.findById(location1.getId()).get();
//                newloc.setDescription("asdqwe");
//                locationRepo.save(newloc);
//            }catch (InterruptedException e){
//                e.printStackTrace();
//            }
//        };
//        Thread t = new Thread(r);
//        t.start();
    }
}